services:
  redis:
    image: redis:latest
    container_name: redis-altamira-participa
    restart: unless-stopped
    ports:
      - '6380:6379'
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - redis_data:/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'redis-cli replicaof no one && redis-cli -a $REDIS_PASSWORD ping'
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  pg:
    image: postgres:18
    container_name: pg-altamira-participa
    restart: always
    ports:
      - '5434:5432'
    shm_size: 2gb

    environment:
      - PGDATA=/var/lib/postgresql/18/data
    env_file:
      - .env
    volumes:
      - ./pg/data:/var/lib/postgresql/18/data
      - ./pg/backup:/var/lib/postgresql/18/backup

    command: >
      postgres
      -c shared_buffers=1536MB
      -c work_mem=4MB
      -c effective_cache_size=5GB
      -c random_page_cost=1.1

    healthcheck:
      test:
        [
          'CMD-SHELL',
          'PGPASSWORD=$${POSTGRES_PASSWORD} pg_isready -h localhost -U $${POSTGRES_USER}'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api-altamira-participa
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/admin
      - REDIS_ADDR=redis:6379
    ports:
      - '3335:3333'

  web:
    depends_on:
      api:
        condition: service_started
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: web-altamira-participa
    restart: unless-stopped
    env_file:
      - ./web/.env
    ports:
      - '5174:5174'

volumes:
  redis_data:
