import type { Metadata } from 'next'
import { Geist_Mono, Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { cn } from 'ui/lib/utils'
import { AuthProvider } from '../hooks/auth-provider'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        geistMono.variable,
        'font-sans',
        inter.variable
      )}
    >
      <body className='flex flex-col justify-center items-center mt-5 mb-30 ml-30 mr-30 dark'>
        <AuthProvider>
          {children}

          <Toaster
            position='top-center'
            theme='dark'
            style={
              {
                '--border-radius': '9999px',
                '--normal-bg': 'oklch(0.21 0.006 285.885)',
                '--normal-border': 'oklch(1 0 0 / 10%)',
                '--normal-text': 'oklch(0.985 0 0)'
              } as React.CSSProperties
            }
          />
        </AuthProvider>
      </body>
    </html>
  )
}
